[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "can>=0.0.0",
    "flask>=3.1.1",
    "python-can>=4.5.0",
]
